spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    com.cryptotrading: DEBUG
    org.springframework.web: DEBUG