spring:
  application:
    name: crypto-trading-system
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:crypto_trading}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:crypto_user}
    password: ${MYSQL_PASSWORD:your_mysql_password_here}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:your_redis_password_here}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# JWT Configuration
jwt:
  secret-key: ${JWT_SECRET_KEY:your_jwt_secret_key_here_minimum_256_bits}
  expiration: ${JWT_EXPIRATION:1800000}
  refresh-expiration: 604800000

# Encryption Configuration
encryption:
  aes-secret-key: ${AES_SECRET_KEY:your_aes_secret_key_here_32_characters}

# Upbit API Configuration
upbit:
  api:
    url: https://api.upbit.com/v1
    access-key: ${UPBIT_ACCESS_KEY:}
    secret-key: ${UPBIT_SECRET_KEY:}
  websocket:
    url: wss://api.upbit.com/websocket/v1

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    root: INFO
    com.cryptotrading: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/crypto-trading.log
    max-size: 10MB
    max-history: 30